### PR TITLE
Editing some junk

### PR DESCRIPTION
**Pull request by QuinnLeavitt**
Improved some things

### CODE REVIEW

**Review by SamBumgardner — CHANGES_REQUESTED** [review]
This takes care of your 3 "edit existing files" commits, but it has the same problem of including unrelated commits from your other branches (since this was created from them instead of from master).

Please follow the steps described here to rebase your branch on to master to properly isolate the changes intended for this branch. https://github.com/SamBumgardner/CSC-303-Git-Playground/pull/94#issuecomment-1429014993

**Comment by SamBumgardner** [comment]
Something has gone very wrong here, I wouldn't expect to see commits from the master branch here. We'll need to do some discussion to untangle this, I think.

**Comment by QuinnLeavitt** [comment]
Yeah I have no idea what happened, I tried following the steps but I think I went wrong because I used the vscode sync while rebasing and I think that caused some errors. That or something is super wrong.

**Review by SamBumgardner — APPROVED** [review]
We did it, the danger is over!

**Pull request merged**
