### PR TITLE
Fork everyone

### PR DESCRIPTION
**Pull request by RPeterson0487**

### CODE REVIEW

**Comment by plasterow** [comment]
Very SUS addition Rick. Thanks for the contribution.

**Review by SamBumgardner — APPROVED** [review]
Nice contributions, glad to see amogus properly immortalized in this repository.

**Review by aarongerbrandt — APPROVED** [review]
This really inspired me :) Excellent work

**Comment by QuinnLeavitt** [comment]
Fork this repo!

**Pull request merged**
