### PR TITLE
Part2

### PR DESCRIPTION
**Pull request by krawcox**
Morning part 2

### CODE REVIEW

**Review by SamBumgardner — CHANGES_REQUESTED** [review]
This branch was created off of your `Nalesniki` branch, but each branch should've been made independently from your `master` branch. This is why all three of your branches have the same first 3 commits.

As a rule, always make your "feature branches" off of `master`, and keep them focused on a single purpose (separate from other "feature branches")

I can merge 1 of your 3 pull requests (you can pick which one) but I need you to make Pull Requests from two other branches off of master that are separate from these 3.

The changes you made look good, the only issue was the way the branches were created.

**Comment by SamBumgardner** [comment]
To avoid this issue in the future, always use `git checkout master` to switch to the master branch before creating a new branch with either `git branch some-branch-name` or `git checkout -b some-branch-name`

**Comment by krawcox** [comment]
Thank you Sam

**Comment by SamBumgardner** [comment]
Closing, since your other 3 pull requests were merged successfully.

**Pull request closed without merging**
