### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Sky322**
one of my three branches

### CODE REVIEW

**Comment by CEckroth** [comment]
I like that you added a zebra.

**Review by SamBumgardner — CHANGES_REQUESTED** [review]
We've got a merge conflict that needs resolving, then you're good to go.

**Comment by CoreyRusher** [comment]
I listened to the psychostick song. I had never heard of them but I love metal music so dope.

**Comment by Sky322** [comment]
should be fixed now

**Review by SamBumgardner — APPROVED** [review]

**Pull request merged**
